### PR TITLE
added MatVec function wrapper for oclBLAS

### PR DESCRIPTION
**Pull request by mapclyps**
From the comment on 4326202 the idea of a function wrapper for calling `MatVec` with disabled buffer synchronization between host and GPU memory came up. Here is a implementation of that suggestion.
I'm not sure if there is a more sophisticated way for the wrapper especially for the arguments. The wrapper leads to one more `#ifdef` for the `MatVec_clBLAS` call. 
@myurkin let me know what you think about it.
We can iterate here to come to a good solution and may add it then as a single commit to master using gits rebase feature. This may also help to not clutter master with tiny changes in PRs when they finally get merged.

### CODE REVIEW

**Comment by myurkin** [comment]
A lot of ifdef-s seems a bit ugly. So I can suggest a few options:
1) move ifdefs into the `MatVec_clBLAS` function (around each of `bufupload=...`)
2) create two instances `MatVec_clBLAS`, separated by ifdefs. (equivalent to 1)
3) created a define, like `MatVec_wrapper`, which based on `OCL_BLAS` will be either simple `Matvec` call or `MatVec` surrounded by `bufupload=...`. The latter can also be a call to existing wrapper.

Solutions 1) and 2) make it reasonable to rename the wrapper to `MatVec_wrapper` as well (or something similar, that would show that it contains both standard and `OCL_BLAS` call). Personally, I slightly favor the option 1), but I haven't really thought a lot about it.

Concerning the function (wrapper) arguments (`restrict`, etc.) - I think they can be safely copied from the declaration of `MatVec` at the top of this file. Please also adhere to existing style guide - see https://github.com/adda-team/adda/blob/wiki/CodeStyleGuide.md (or just look at existing functions).

**Comment by mapclyps** [comment]
The function is renamed now to `MatVec_wrapper` and is always called currently in the bicg solver. Ifdefs are around `bufupload` and it works also in seq mode.
The `restrict`s and style are changed. 
So I went for the 1) option. I think for now it should be okay. Maybe in future changes here may become less transparent as now there is another layer around around `MatVec`.
If you are okay with the change I would rebase and merge it (I am curious about the rebasing, hence the self asign)

**Comment by myurkin** [comment]
I have proposed some syntax changes through pull request (also, experimenting with new features). Apart from that, everything seems fine. So continue with merging.

But please test that the final version compiles and runs fine. And please also test `./adda -recalc_resid` just in case (I have minor concerns from quick look at the code, hopefully unfounded).

**Comment by mapclyps** [comment]
It seem to work fine. I tested also `-recalc_resid` and the residual was practically the same as in the last iterations except for the rounding of the last digit. I joined all commits to one single commit and left the commit message of the first commit where the intention was described; so I merge this now

**Pull request merged**
