### PR TITLE
new shape coated2

### PR DESCRIPTION
**Pull request by Mercede-hash**
_Thank you for contributing to ADDA. Please remove the Italic text (`_..._`) throughout this template after following the corresponding instructions_

### Description
_Please explain the changes you made here. Answer both why and what_

### Related issues
_Any nontrivial pull request should first be discussed in the issue_ 

Fixes #...  or Related to #...

### Types of changes
_What types of changes does your code introduce to ADDA? Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [contributing guidelines](https://github.com/adda-team/adda/blob/master/.github/CONTRIBUTING.md)
- [x] Code compiles correctly
- [ ] Tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works. And these tests pass
- [ ] I have added/extended necessary documentation (if appropriate)

### Further comments
_If this is a relatively large or complex change, explain why you chose the solution you did and what alternatives you considered. 
If that was discussed in issue or somewhere else, refer to it here_

### CODE REVIEW

**Comment by Mercede-hash** [comment]
This is a new structure, called coated2, which is basically a simple core-shell structure containing a second shell around the first one (a core-shell-shell structure if you want so).

**Comment by myurkin** [comment]
Mercede, can you please use the latest state of adda:master as a basis for this pull request? It seems that you missed a couple of latest commits.

**Comment by Mercede-hash** [comment]
Hi Maksim, sorry seems like I pushed the wrong files before (554c25c), but I added the "corrected" ones as well now (72c89a4).

**Comment by myurkin** [comment]
Mercede, I have committed some changes to your branch. Please verify that it works fine on your side (and produces consistent results). After that I will merge it.

**Comment by Mercede-hash** [comment]
Hi Maxim,

Everything works fine from my side and gives reasonable results.

Best,
Mercede

Am Freitag, 23. April 2021 schrieb Maxim Yurkin ***@***.***>:

**Pull request merged**
