### PR TITLE
fix: reflect new file layout of .geom files in near_field

### PR DESCRIPTION
**Pull request by timovanopstal**
### Description
`misc/near_field/gendip.f` seems to read `.geom` files incorrectly. Corrected and tested on `./runexample`

### Related issues

Fixes #...  or Related to #...

### Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/adda-team/adda/blob/master/.github/CONTRIBUTING.md)
- [x] Code compiles correctly
- [x] Tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works. And these tests pass
- [ ] I have added/extended necessary documentation (if appropriate)

### CODE REVIEW

**Comment by myurkin** [comment]
The fix is good. Thanks! The extra line in geometry files appeared due to recent incorporation of rectangular dipoles.
Can you additionally run the tests at `RUNEXAMPLE/runall` ?

**Comment by timovanopstal** [comment]
Ok, I force-updated my fix. Do you mean `misc/near_field/RUNTESTS/runall`? In that case, now they pass.

**Comment by myurkin** [comment]
Timo, sorry for the delay. I have been at the conference previous week. I have tested your fix, and it works fine. However, I want to take this opportunity and fix a couple of related issues in near_field and combine it into this pull request. This may take a couple more days.

**Comment by myurkin** [comment]
Timo, I have fixed everything I wanted and pushed it to your branch (so it automatically updated this pull request). Can you please test the current state - both compiling and `RUNTESTS/runall`? For the latter please also check that the produced numbers are small.

**Comment by timovanopstal** [comment]
I've rerun tests and they still work. As an aside, I'm on OS X with GNU Fortran from Homebrew (GCC 8.2.0) and to get things to compile, I had to
```
-MPIFC  = $(FC)
+MPIFC  = mpifort
 LIBS   =
-MPILIBS= -lfmpich2g
```

**Comment by timovanopstal** [comment]
Oh, and a more important remark, you added `coated/run` but without execution permissions, so it didn't run with `./runall` although the test does pass.

**Pull request merged**
